on: push

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml

  integration-tests:
    uses: ./.github/workflows/integration-tests.yml

  build-x64-ubuntu-2204:
    uses: ./.github/workflows/build-x64-ubuntu-2204.yml

  build-x64-centos-stream-8:
    uses: ./.github/workflows/build-x64-centos-stream-8.yml

  build-x64-centos-7:
    uses: ./.github/workflows/build-x64-centos-7.yml
